project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!assignments/files/"
    - "!files/tutorials/"   

website:
  title: "E655 - Econometrics"
  navbar:
    pinned: true
    background: "#9e32a8"
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Assignments"
        file: assignments/index.qmd

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
      
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Course content"
          contents:
            - text: "Introduction to R"
              file: content/introtor.qmd
            - text: "Matrix Review"
              file: content/matrixrev.qmd
            - text: "Regression"
              file: content/regression.qmd
            - text: "Causality"
              file: content/causality.qmd
            - text: "OLS"
              file: content/ols.qmd
            - text: "Instrumental Variables"
              file: content/iv.qmd 

    - title: "Assignments"
      style: "docked"
      search: false
      background: dark
      contents:
      
        - section: "Overview"
          contents:
            - assignments/index.qmd
        - section: "Intro to Quarto"
          contents:
            - assignments/introtoquarto.qmd
        - section: "Assignments"
          contents:
            - text: "Assignment 1"
              file: assignments/assign1.qmd
            - text: "Assignment 2"
              file: assignments/assign2.qmd  

format:
  html:
    code-overflow: wrap
    theme: 
      - litera
      - html/custom.scss
    toc: true


