project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "E655 - Econometrics"
  navbar:
    pinned: true
    background: "#9e32a8"
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - text: "Content"
        file: content/index.qmd

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Course content"
          contents:
            - text: "Introduction to R"
              file: content/introtor.qmd
            - text: "Matrix Review"
              file: content/matrixrev.qmd

format:
  html:
    theme: 
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai


