---
title: "Causality"
---


## Readings

- AP1 Chapter 3
- AP2 Chapter 2
- C "Properties of Regression"
- CT Chapter 4
- HA Chapters 2,3,4
- HK Chapter 13
- K Chapter 3
- SW Chapters 4,5,6,7,8
- W1 Chapter 4
- W2 Appendix E

## Slides

The slides are embedded in this page, and you can scroll through them with the arrow keys.  If you prefer you can instead <a href="/slides/causality/index.html" target="_blank">pop them out in a new window</a>


<div>

```{=html}
<p align="center"><iframe width="890" height="500" class="slide-deck" src="/slides/causality/"></iframe></p>
```

</div>


## Videos

This is a lecture from (recent Nobel Prize winner) Joshua Angrist explaining these same ideas as part of a lecture series from the American Economics Association (no preview available). <a href="https://events7.mediasite.com/Mediasite/Play/68970a31745148a98e5be9df3e99f59f1d" target="_blank">View video</a>

## Tutorials

The tutorial below covers the basics on how to plot DAGs in R.  

<div>

```{=html}
<p align="center"><iframe height="500" width="100%" frameborder="no" src="http://3.145.56.130:3838/EC655dag/"> </iframe></p>
```

</div>

## Other Resources

[daggity.net](https://dagitty.net) - Website where you can create and analyze DAGs.  Will help you determine whether you can identify direct effects by controlling for variables in a model.  Also tells you testable model implications and gives code to plot DAG in R.


