---
title: "Introduction to R"
---

## Readings

Hanck, C., Arnold, M., Gerber, A., & Schmelzer, M. (2019). Introduction to Econometrics with R. University of Duisburg-Essen. Url: <https://www.econometrics-with-r.org>

Oswald, F., Viers, V., Robin, J.- M., Villedieu, P., Kenedi, G. (2020). Introduction to Econometrics with R. Department of Economics, Sciences Po. Url: <https://scpoecon.github.io/ScPoEconometrics/>

## Tutorial

The .zip file below contains the files to run a `learnr` interactive tutorial.  To use it, first ensure that you have installed the `learnr` and `shiny` packages.  Then, download the file, unpack it, open the .Rmd file in RStudio, and click "run document."

There is also a plain, non-interactive PDF version of the file below.

[{{< fa solid file-export >}} `EC655learnr.zip`](/files/tutorials/EC655learnr.zip)

[{{< fa solid file-export >}} `EC655learnrpdf.pdf`](/files/tutorials/EC655learnrpdf.pdf)


## Videos

### Introduction to R by Nick Huntington-Klein

Economist Nick Huntington-Klein has produced a series of videos that cover how to use R for economists. The series is broken into beginner, intermediate, and advanced levels.

{{< video https://www.youtube.com/watch?v=kD1qq5tBrLg&list=PLcTBLulJV_AIuXCxr__V8XAzWZosMQIfW&index=1 width="400" height="300" title="Intro to R for Economists by Nick H-K" >}}

## Other Resources

- [R Studio Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/)

These provide a quick reference sheet for common packages in R, with examples on how to use them.  A very valuable resources for both beginners and more advanced users.

- [Swirl Package](https://swirlstats.com/students.html)

This package is designed to help you learn R within R itself.  There are several tutorials available that guide you throught the various topics.
