---
title: "Ordinary Least Squares"
---


## Readings

- AP1 Chapter 3
- AP2 Chapter 2
- C Chapter 2
- CT Chapter 4
- HA Chapters 3,4
- HK Chapter 13
- K Chapter 3
- SW Chapters 4,5,6,7,8
- W1 Chapter 4
- W2 Chapters 2,3

## Slides

The slides are embedded in this page, and you can scroll through them with the arrow keys.  If you prefer you can instead <a href="/slides/ols/index.html" target="_blank">pop them out in a new window</a>


<div>

```{=html}
<p align="center"><iframe width="890" height="500" class="slide-deck" src="/slides/ols/"></iframe></p>
```

</div>

## Tutorials

The .zip file below contains the files to run a `learnr` interactive tutorial.  To use it, first ensure that you have installed the `learnr` and `shiny` packages.  Then, download the file, unpack it, open the .Rmd file in RStudio, and click "run document."

There is also a plain, non-interactive PDF version of the file below.

[{{< fa solid file-export >}} `EC655regression.zip`](/files/tutorials/EC655regression.zip)

[{{< fa solid file-export >}} `EC655regressionpdf.pdf`](/files/tutorials/EC655regressionpdf.pdf)

[{{< fa solid file-export >}} `EC655hypothesis.zip`](/files/tutorials/EC655hypothesis.zip)

[{{< fa solid file-export >}} `EC655hypothesispdf.pdf`](/files/tutorials/EC655hypothesispdf.pdf)


