---
title: "Introduction to Quarto"
---

## Tutorial

The .zip file below contains the files to run a `learnr` interactive tutorial.  To use it, first ensure that you have installed the `learnr` and `shiny` packages.  Then, download the file, unpack it, open the .Rmd file in RStudio, and click "run document."

There is also a plain, non-interactive PDF version of the file below.

[{{< fa solid file-export >}} `EC655quarto.zip`](/files/tutorials/EC655quarto.zip)

[{{< fa solid file-export >}} `EC655quartopdf.pdf`](/files/tutorials/EC655quartopdf.pdf)

## Videos

### Introduction to Quarto by Dr. Lyndon Walker

A video introduction to Quarto

{{< video https://www.youtube.com/watch?v=y5VcxMOnj3M width="400" height="300" title="Intro to Quarto by Dr. Lyndon Walker" >}}

## Other Resources

- [Quarto Website Reference Section](https://quarto.org/docs/reference/)

The Quarto website has a very good reference section for any type of document you want to produce.  Navigate to the PDF section for help with formatting your assignments.

- [Quarto Cheat Sheet](https://images.datacamp.com/image/upload/v1676540721/Marketing/Blog/Quarto_Cheat_Sheet.pdf)

Like with the RStudio cheat sheets, this provides a quick overview of the ways you can interact with Quarto
